apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-deploy
spec:
 replicas: 7
 template:
  metadata:
   labels:
    app: my-deploy
  spec:
   containers:
   - name: nginx
     image: nginx:1.9
     ports:
     - containerPort: 80
     resources:
      limits:
       cpu: 100m
       memory: 500Mi
 selector:
  matchLabels:
   app: my-deploy
