apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
spec:
 capacity:
  storage: 1Gi
 hostPath:
  path: /tmp/pv1
  type: DirectoryOrCreate
 accessModes:
 - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv2
spec:
 capacity:
  storage: 500Mi
 hostPath:
  path: /tmp/pv2
  type: DirectoryOrCreate
 accessModes:
 - ReadWriteOnce
