apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: my-rs
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: my-rs
  spec:
   containers: 
   - name: nginx
     image: nginx
     ports: 
     - containerPort: 80
     resources:
      limits:
       cpu: 100m
       memory: 500Mi
 selector:
  matchLabels:
   app: my-rs
